name: Version Sync and CDN Tag
on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version tag
        run: |
          DATE_VERSION=$(date +'v%Y.%m.%d')
          COMMIT_COUNT=$(git rev-list --count HEAD)
          NEW_TAG="${DATE_VERSION}-${COMMIT_COUNT}"

          # Update HTML references
          sed -i "s/@v[^\/]*/@${NEW_TAG}/g" index.html
          sed -i "s/?v=[^\"']*/?v=${NEW_TAG}/g" index.html

          # Commit and tag
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Auto-version ${NEW_TAG}"
          git tag ${NEW_TAG}
          git push origin ${NEW_TAG}
          git push